[package]
name = "rlex"
version = "0.1.10"
edition = "2021"
license = "MIT OR Apache-2.0"
description = "A cursor-based, utf-8 Vec<char> lexer."
repository = "https://github.com/phillip-england/rlex"

[dependencies]
